package main

import (
	"fmt"
	"io"

	"github.com/phoban01/fluxlint/pkg/lint"
)

var ruleFamilies = []struct{ prefix, title, intro string }{
	{"FL-G", "Graph", "Whether the components can converge at all: references, ownership and ordering."},
	{"FL-S", "Substitution", "Post-build variables: where they come from and whether they resolve."},
	{"FL-V", "Validation", "Whether the API server will accept what is rendered."},
	{"FL-R", "Runtime", "Whether pods can start once their objects are applied."},
	{"FL-C", "Contracts", "What a controller or chart declares it cannot run without."},
	{"FL-A", "Assertions", "Your own rules, written in CEL."},
	{"FL-D", "Transitions", "What reconciling a change does to a cluster that runs the base. Needs `--base`."},
	{"FL-X", "Sources and rendering", "What fluxlint could not fetch or does not model."},
	{"FL-T", "Timing", "How long a bootstrap can take, and why."},
}

// writeRulesDoc prints the rule reference published on the docs site. It is
// generated from the catalogue so the two cannot drift apart.
func writeRulesDoc(w io.Writer) {
	fmt.Fprint(w, "# Rules\n\n<!-- Generated by `fluxlint rules --markdown`. Do not edit. -->\n\n")
	fmt.Fprint(w, "Every finding carries a rule ID. `fluxlint explain <id>` prints the same text as this page.\n")
	fmt.Fprint(w, "Change a rule's severity, or turn it off, under `rules:` in [`.fluxlint.yaml`](configuration.md).\n")
	for _, fam := range ruleFamilies {
		fmt.Fprintf(w, "\n## %s\n\n%s\n", fam.title, fam.intro)
		for _, r := range lint.Rules {
			if len(r.ID) < len(fam.prefix) || r.ID[:len(fam.prefix)] != fam.prefix {
				continue
			}
			fmt.Fprintf(w, "\n### %s %s\n\nDefault severity: **%s**\n\n%s\n", r.ID, r.Name, r.Severity, r.Help)
		}
	}
}
